### ISSUE TITLE
Quiz results could be more color-weakness friendly

### ISSUE THREAD

**Issue by sateffen** [Green-Software-Foundation/learn#139]
**Describe the bug**
The borders of quiz-answers after checking the results are non easily distinguishable. I can't tell whether it's green or red, but have to assume "one border = right, two borders = wrong".

**To Reproduce**
1. Go to 'https://learn.greensoftware.foundation/carbon-efficiency'
2. Scroll down to the quiz
3. Click something wrong in the quiz (this is the simplest way to get red + green besides each other)
4. Check your answers

**Expected behavior**
I expected to see the difference between right and wrong answers more clearly while scrolling over these, but can't differenciate the borders that easily.

**Screenshots**
![grafik](https://user-images.githubusercontent.com/2326181/208427307-38715dc1-0e5e-445e-8402-82a05c728674.png)

**Desktop (please complete the following information):**
 - OS: Arch Linux (I use Arch btw)
 - Browser Firefox
 - Version 108.0.1

**Additional context**
I have difficulties differentiating colors (basically I'm green-weak, but I think based on my monitors the contrast might even be another problem). Based on the assumption "one border = right, two borders = wrong" it works, but I personally think this should be more "inclusive" in one or two ways:
 - You could use a background-color, that's a lighened version of the border. That way it gets simpler to see right and wrong answers.
 - You could use an additional icon floating on the right of the answer, helping people with difficulties differentiating red/green.

**Comment by holanita** [comment]
Hi @sateffen thank you for your comment. Note that our team will only be able to pick this up in the new year. Thanks for your patience and happy holidays.

**Comment by jawache** [comment]
Hi @osamajandali can you take a look at this issue? Adding it to the web board

**Comment by zanete** [comment]
Capturing the status during weekly web call:
- on hold last week, @osamajandali will add an icon to the correct and incorrect answers this week

**Comment by osamajandali** [comment]
Now it shows an icon beside the correct/incorrect answers


![Image](https://user-images.githubusercontent.com/13832392/223004339-f0045f0b-2988-4056-9c91-3cc1a54dfd03.png)

**Comment by jawache** [comment]
Thanks @osamajandali, @sateffen does this work for you?

**Comment by jawache** [comment]
Amazing, cc/ @greenhsu123 FYI
