### ISSUE TITLE
Event(s) for Earth Day

### ISSUE THREAD

**Issue by holanita** [Green-Software-Foundation/learn#142]
Why: to promote the course and get as many people as possible to complete the course and share their certificate online.
What: organize a Trending Event During Earth Week, just a moment in time and not necessarily a real event.
Who: this task should be driven by the Community Working Group, tasks owners are still to be confirmed.
When: Earth Day, April 22 / Earth Week, April 16-22
Next step: details to be discussed in the next Community Working Group call in January 2023.

To be discussed:
- title/slogan: **'Do the training on Earth Day'** / **'Green Software Day'**?
- is this just a moment in time or will we do some kind of a Meetup event as well?
- if so, who can host that event? who else can participate / speak at the event?
- what should be the agenda of the day / event
- what content and design assets do we need to promote this?
- who is available to work on this and what tasks can they take on?

**Comment by greenhsu123** [comment]
We should delay the promotional event till July/August when most member organisations have summer interns. This could drastically increase the take-up of the course. 

Event concept:
A week where each region/city competes on the total # of course completion. 

Event format:
- Virtual teaching of Principles of Green Software
- Live teaching @ regional meetups or internal events of Principles of Green Software

Event DateTime:
- Last week of July

**Comment by greenhsu123** [comment]
Per @tmcclell and @tadanna: this will be discussed further in the next community WG call.

**Comment by greenhsu123** [comment]
As per the Community WG meeting yesterday, we have decided against organising meetup-styled events for Earth Day 2023

cc: @tmcclell @jawache
