### ISSUE TITLE
Add "designing" to the "who should read this" in certification 

### ISSUE THREAD

**Issue by etoldani** [Green-Software-Foundation/learn#160]
As I took the Green Software for Practitioners training. One of the first paragraphs was about who should take the training. Today it says, "Anyone involved in the process of building, deploying, or managing software." I was taken aback that designers and architects were not included. As the upfront creators, innovators, designers, and architects, these groups of people are making upfront decisions about the product before any building, developing, or managing of the software happens. Many decisions can and will be made upfront with regards to the product's impact. I think it would be crucial for these folks to be included in the list and encouraged to also take this training. As a Senior UX Designer, I am working to compile principles that can be included into the product's discovery and exploration phases around building more sustainable and less impactful products from the very beginning.  I think this would be great to include. I am also aware of other various Green Principles and practices from Microsoft and other place ClimateAction.tech #green-design that could be incorporated as well. I think having those roles included as part of the "practitioners" would be a great first step.

**Comment by holanita** [comment]
Hi @etoldani many thanks for your comment. Assigning @greenhsu123 for review and feedback.

**Comment by greenhsu123** [comment]
Hi @etoldani, thank you very much for your feedback. I wholeheartedly agree that this course is not just for software engineers/developers but everyone in the software business, including designers, product managers, architects, etc. 

This is an oversight on our end, so we will look to update the content on the Linux Foundation site. However, please rest assured that our intention for this variation of the course is for all software practitioners, as detailed [here](https://learn.greensoftware.foundation/#what-is-a-software-practitioner).
