### ISSUE TITLE
Possibility to subscribe to the newsletter from the GSF learn website

### ISSUE THREAD

**Issue by Oleg-Zhymolokhov** [Green-Software-Foundation/learn#167]
As a person visiting the [learn website](https://learn.greensoftware.foundation/) I want to have the ability to subscribe to a newsletter so that I can get updates on the GSF activities.

- [x] Come up with the design (including mobile devices)
- [x] Implement the functionality

**Comment by Oleg-Zhymolokhov** [comment]
@jawache please feel free to review it and add your comments if there are any.

**Comment by osamajandali** [comment]
@Oleg-Zhymolokhov do you want to add it in ever page on specific pages only?

**Comment by Oleg-Zhymolokhov** [comment]
Ideally, yes, but in a non-intrusive way, so people wouldn't skip it.

**Comment by zanete** [comment]
Capturing the status during the weekly call:
- adding this issue to the web board for this week
- @osamajandali has access to Mailchimp but might need @jawache help in creating the form in mailchimp for integration (FYI)
- @osamajandali will work on the design and get that confirmed in the meantime

**Comment by osamajandali** [comment]
@Oleg-Zhymolokhov  @zanete  I made the design the design 
![image](https://user-images.githubusercontent.com/13832392/229981369-e3e6d2e6-40cd-4ac1-915d-6a2780851961.png)

- I make it so obvious so we grab people's attention and then they don't skip
- I need the copy for the **Title** and the **Subtitle**
- Will it be positioned on the very end of each page or we will select some places to put it?
- if the previous is **yes**, then I need to know those places

**Comment by zanete** [comment]
Capturing status of weekly call:
- @Oleg-Zhymolokhov can we count on you to coordinate answers to the above and feedback on the design?

**Comment by jawache** [comment]
@osamajandali FYI these subscribers should go to the main Mailchimp audience, "Green Software Foundation", ideally with a "tag" so we can know they came from the learn training. https://mailchimp.com/help/getting-started-tags/

**Comment by zanete** [comment]
@Oleg-Zhymolokhov - we have the web weekly call this Wednesday, let me know if you will have a chance to comment on https://github.com/Green-Software-Foundation/learn/issues/167#issuecomment-1496905753 by then

**Comment by zanete** [comment]
Capturing the status in weekly call:
- still awaiting comments from @Oleg-Zhymolokhov , but I take this project is currently on hold awaiting a new PM, will keep this on hold until we hear otherwise.

**Comment by Oleg-Zhymolokhov** [comment]
@zanete not sure how I didn't see this, I'm sorry. I will coordinate this.

**Comment by Oleg-Zhymolokhov** [comment]
@osamajandali @jawache As for me, having it at the bottom of the page is fine and less intrusive for users. I like the design though - impossible to miss it.

**Comment by Oleg-Zhymolokhov** [comment]
@NAMRATA-WOKE Could you come up with a Title and the Subtitle for the functionality above?

**Comment by zanete** [comment]
Capturing status in the weekly call:
- @NAMRATA-WOKE let us know if you have had a chance to suggest Title and Subtitle for this, I have added this to the marketing board, too

**Comment by NAMRATA-WOKE** [comment]
@osamajandali @zanete 

Subscribe for Weekly Green News! 

Get the latest information and resources to help you decarbonize your software and build momentum towards cleaner and more energy efficient software!

**Comment by NAMRATA-WOKE** [comment]
@osamajandali will you let me know when this has been completed?

**Comment by osamajandali** [comment]
Done
cc: @NAMRATA-WOKE

**Comment by zanete** [comment]
Thanks so much, looks great!
