### ISSUE TITLE
Create a temporary badge for the Green Software Practitioner exam successful completion

### ISSUE THREAD

**Issue by Oleg-Zhymolokhov** [Green-Software-Foundation/learn#170]
We need a temporary badge for the Green Software for Practitioners course. 

The current badge looks like this and does not represent the contents of the course, thus we need something to change it.

- Use the dimensions of the original image;
- Create a new badge following the styles of the GSF.

![Image](https://user-images.githubusercontent.com/125550685/230349972-ee2d1f8c-f0e4-4f06-ac14-0608cf131755.png)

**Comment by Jenya-design** [comment]
@Oleg-Zhymolokhov please check the option attached and let me know if you ned any adjustments
Size 1000x1000 px, png and ai source files on GSF drive [here ](https://drive.google.com/drive/folders/1aOIUO4Rc4cvK_K5fDaRUsy18GWVPaPIL?usp=share_link)

![01_badge_GS Practitioner-01](https://user-images.githubusercontent.com/69306070/230429025-157f096d-5379-40ab-aedd-ab436f4138e6.png)

![01_badge_GS Practitioner-02](https://user-images.githubusercontent.com/69306070/230429033-bf048a5d-f382-4dc8-b859-4fa1138b7f66.png)

![01_badge_GS Practitioner-03](https://user-images.githubusercontent.com/69306070/230429035-c3369ba0-4efb-40e6-b2b9-a40b0cc36c17.png)

**Comment by Oleg-Zhymolokhov** [comment]
@NAMRATA-WOKE what do you think on these? I'd pick 1st or 3rd and leave them as they are.

**Comment by NAMRATA-WOKE** [comment]
@Oleg-Zhymolokhov @Jenya-design id go with the first option.
