### ISSUE TITLE
Measurement page shows incorrect formula

### ISSUE THREAD

**Issue by DuncsGhyston** [Green-Software-Foundation/learn#172]
**Describe the bug**
The measurement page includes the SCI equation as a nice graphic, but underneath the equation is repeated incorrectly. It suggests we should multiply by `M`, when the graphic above suggests we should add `M`. This is pretty confusing when learning about the formula for the first time.

https://learn.greensoftware.foundation/measurement#the-sci-equation

The formula currently reads `SCI = ((E *I) * M) per R` which is incorrect.

**Expected behavior**
The formula should read `SCI = ((E *I) + M) per R`

**Screenshots**
![image](https://user-images.githubusercontent.com/102806252/234581290-b41a5613-604b-4f61-84e6-e6ed11260bb8.png)

**Comment by greenhsu123** [comment]
Great spot, thanks for flagging! The issue should be resolved now.
