### ISSUE TITLE
Contributing a German translation

### ISSUE THREAD

**Issue by renao** [Green-Software-Foundation/learn#173]
Hello everyone,

I'm glad that I found the Green Software Foundation on my journey to find more standards/principles for creating more sustainable software.

After having a good time on your learn page I'd like to share the page with in our company but unfortunately they are not that fluent in English (especially in the electricity and sustainabilty domain) and/or they have to be inspired to make greener software in the future.

So I'd like to contribute a German translation to lower the obstacles to get them started 🙂

I already recognized the Italian localization by @childotg but I began to stumble when I tried to understand how the translations are handled when I started the dev server locally and I always ended on a 404 page, even it seems to lead me to the correct location, e.g. `localhost:3000/it/`.

Is there a way I can ge things working locally?
I am an experienced dev but not really a js/docusaurus-hero 😬 

Anyway I'd go on and start translating the markdown files putting them into a `i18n/de` folder, like things have been done for the Italian language before.

Have a nice day!

**Comment by childotg** [comment]
Hello @renao, when you start docusaurus it starts just a single language with the "yarn run start --locale de" directive. You can find more details here: https://docusaurus.io/docs/i18n/tutorial.
Don't worry about in debug you can just see a single language, when the project builds it will generate others.

**Comment by renao** [comment]
Thanks a lot @childotg , that'll make things much easier seeing the translations in their context.
I'll give it a shot at the weekend!

**Comment by russelltrow** [comment]
Hey @renao did you manage to make any progress? Do you require any further support?

**Comment by renao** [comment]
Hey @russelltrow thanks for your reply. I have been busy the last months so I had to stop translation.
I'll continue soon, I promise :)

**Comment by markus-gsf-seidl** [comment]
@renao Do you have a repository setup where others can contribute?

**Comment by russelltrow** [comment]
Hey @renao checking in to see if you are still progressing with your translation?

**Comment by renao** [comment]
Hey @russelltrow , hey @markus-gsf-seidl ,
sorry for coming back at you this late. Life just wanted me to spent the time in another way.

I had issues translating the carbon-domain specific/scientific terms at that time. Perhaps there is someone who has a good grasp on that domain in german. That is where my translation work got stuck and I started doing other things.

I translated the pages locally and just a few weeks ago I deleted the repository - sorry.

Well, if there will someone join with the needed background knowledge, I would help surely.

**Comment by cdhaens** [comment]
Hi, I'll gladly contribute to the German translation. Please let me know how I can best support. Take care, Carolin

**Comment by childotg** [comment]
Hello! If you want support on how I translated Italian we can for sure setup a call!

**Comment by franziska-warncke** [comment]
@childotg  Yes, this would be great! Can you setup a meeting? 
@cdhaens Did you already started something?

**Comment by russelltrow** [comment]
Fantastic to see this starting up again! 

For reference I recently merged a Japanese translation so you can see all the changes required: https://github.com/Green-Software-Foundation/learn/tree/translation-jp

**Comment by russelltrow** [comment]
Hey @franziska-warncke @childotg @cdhaens did you manage to meet and discuss the German translation?

**Comment by russelltrow** [comment]
Hey @franziska-warncke @childotg @cdhaens as requested I've created instructions on how to translate the course:

https://github.com/Green-Software-Foundation/learn/blob/main/CONTRIBUTING.md#contributing-a-translation

This includes a template locale that you can duplicate and update accordingly.

**Comment by franziska-warncke** [comment]
Thanks @russelltrow for creation of a guide on how to translate the course. I already started with it. 
To the others: Please feel free to have a look. 
I did not started to translate the images yet.  I think I need the original files for that. Please can you provide this to me @russelltrow? 
https://github.com/Green-Software-Foundation/learn/pull/227

**Comment by russelltrow** [comment]
Hey @Jenya-design what is the best way for @franziska-warncke to translate the images in the course?

**Comment by Jenya-design** [comment]
@russelltrow @franziska-warncke this what I suggest, let me know if it won't work for you
1. Please make a copy of  [this canva template](https://www.canva.com/design/DAFw4Qlvhzw/DDrFtOd-kACi_zrC2L4bSw/edit?utm_content=DAFw4Qlvhzw&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton)
2. Make a translation (text is editable)
3. Tag me here or directly in canva, so I could adjust the design in your canva file - I assume text in German will take more space
After that we can export as png and use 
Thank you

**Comment by franziska-warncke** [comment]
Hi @russelltrow. I was on vacation the last weeks. I will have a look 🌻

**Comment by franziska-warncke** [comment]
Hi, I worked on the review and translated also the pictures. @Jenya-design can you have a look at this: https://www.canva.com/design/DAGJbwbekFc/5PKmgbPe1Iw73JsEF_sVGg/edit?utm_content=DAGJbwbekFc&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton

**Comment by franziska-warncke** [comment]
Ah and so far, the link you provided, there were only 2 pictures available for translation. Where can I find the other ones? 
Sorry if I missed them. :)

**Comment by Jenya-design** [comment]
Thank you @franziska-warncke I applied minor changes for the 1st image to make the space between the text blocks more even, please review
For the rest of the images I can't provide the editable canva versions right away, you didn't miss them. I think the team that made Italian version also made the images adaptation. Let me check what I can do with those

**Comment by Jenya-design** [comment]
@franziska-warncke @russelltrow 
I've added the rest of the images (I didn't include those without text) from [the course](https://learn.greensoftware.foundation/) to [this canva template](https://www.canva.com/design/DAFw4Qlvhzw/DDrFtOd-kACi_zrC2L4bSw/edit?utm_content=DAFw4Qlvhzw&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton) so they now have editable English text you can use for translation. 
Please let me know if you spot any missing elements or mistakes

**Comment by franziska-warncke** [comment]
@Jenya-design I translated all. Can you have a look?https://www.canva.com/design/DAGJbwbekFc/5PKmgbPe1Iw73JsEF_sVGg/edit?utm_content=DAGJbwbekFc&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton

**Comment by Jenya-design** [comment]
Thank you @franziska-warncke
I've added minor adjustments on slides 7-10 and 15-18, mostly alignment and adding boldness
Please feel free to change back if some of those changes are bad for translation, like prepositions should be on previous line etc

**Comment by russelltrow** [comment]
Thank you so so much @franziska-warncke @cdhaens @tamarau for all your efforts, the PR has just been merged and the translation is now live:

https://learn.greensoftware.foundation/de/

🎉 🎉 🎉 🎉 🎉 🎉 🎉
