### ISSUE TITLE
Eco mode is an example of demand shaping - not shifting

### ISSUE THREAD

**Issue by oktobit-de** [Green-Software-Foundation/learn#180]
**Describe the bug**
In the section https://learn.greensoftware.foundation/carbon-awareness you can read: "Eco mode is an example of demand shifting. "

**Expected behavior**
"Eco mode is an example of demand shaping. "

**Additional context**
Shifting and Shaping were simply mixed up.

**Comment by greenhsu123** [comment]
Great catch; thank you for flagging it!
