### ISSUE TITLE
Add a simple web server system as an example for SCI = ((E *I) + M) per R

### ISSUE THREAD

**Issue by fnaith** [Green-Software-Foundation/learn#181]
**Is your feature request related to a problem? Please describe.**
I don't quite understand about how to apply this formula to my system.

**Describe the solution you'd like**
For a web service W at a country C, could you give some numbers and do the actual calculation as example ?

**Describe alternatives you've considered**
nope.

**Additional context**
Do you calculate SCI for your website ?

**Comment by russelltrow** [comment]
Hi @fnaith thank you so much for your feedback, sorry that it has taken so long to respond.

Is your query in regards to how the SCI specification is [described within the course](https://learn.greensoftware.foundation/measurement) or are you looking for guidance on how you can apply SCI for yourself?

We have our [SCI Guide](https://sci-guide.greensoftware.foundation/) which might help make SCI a little clearer.

Please let me know how I might assist further.

**Comment by fnaith** [comment]
I just thought the SCI formula could be better understood if there is an example application.
