### ISSUE TITLE
Chinese translation

### ISSUE THREAD

**Issue by russelltrow** [Green-Software-Foundation/learn#184]
### Discussed in https://github.com/Green-Software-Foundation/learn/discussions/171

<div type='discussions-op-text'>

<sup>Originally posted by **greenhsu123** April 17, 2023</sup>
Community members have proposed that they would like to translate the V1 into Chinese. 

from @Jjing-Liang:
_I'm Jing, a developer from China, I learned through GSF newletter that there is an Italian version, and some of us want to translate a Chinese version so that more Chinese people can learn about green software.
Can we refer to the previous process to participate in it? Or what is the process or requirements for translation participation?_

For details on the previous process, please look at the Italian [MR](https://github.com/Green-Software-Foundation/learn/pull/151). 

Tl:dr: once you and your team have finished translating the principles into Chinese, please raise a PR. We would then start a translation review there while connecting you with the GSF's designer to work on the graphics translation. 

cc: @jawache, @Oleg-Zhymolokhov </div>

**Comment by russelltrow** [comment]
Hey @Jjing-Liang the PR is merged and the translation is now live! https://learn.greensoftware.foundation/zh-CN/

Thank you so much for all your efforts and support with this. We will make sure to start promoting it within our networks.

cc: @greenhsu123 @NAMRATA-WOKE

**Comment by Jjing-Liang** [comment]
Really exciting!! Thanks @russelltrow for all the support!
Also thank again to all of our team members from Thoughtworks for their contributions to the translation: @Irenia111 , Rui Bian, QunYao Cai, Xiantong Cheng, Ying Fu, Aifei Lu, Guanyun Lu(malbona) and Zhaosen Wen!
