### ISSUE TITLE
Training Link? Green Software for Practitioners (LFC131)

### ISSUE THREAD

**Issue by russelltrow** [Green-Software-Foundation/learn#194]
### Discussed in https://github.com/orgs/Green-Software-Foundation/discussions/57

<div type='discussions-op-text'>

<sup>Originally posted by **benlogan** September 14, 2023</sup>
We seem to have lost a direct link to our training course from our homepage?

I know the banner was replaced to promote the State Of report, but wasn't that the main CTA for training?

@seanmcilroy29 @adamj89 any ideas, am I missing something - I had a good poke around!

Green Software for Practitioners (LFC131)
https://training.linuxfoundation.org/training/green-software-for-practitioners-lfc131/</div>

**Comment by zanete** [comment]
@russelltrow If the banner was the main CTA, then that's a bit worrying. 
* It is now promoting Decarb and can't really be used for training. 
* The project list is supposed to take everyone to the Wiki of the respective project, and the Wiki does have a link to training
* That is probably not ideal, and need to find a better spot for it. Can we discuss with the team in a face to face meeting, eg. OKR review or the Solution factory?

cc @jawache

**Comment by russelltrow** [comment]
The main website navigation is going to be redesigned and will include a clear link to the training
