### ISSUE TITLE
Dutch translation

### ISSUE THREAD

**Issue by EdgarPost** [Green-Software-Foundation/learn#195]
I started doing the course and found there it was so far only translated into Italian, but a Chinese and German version are on the way, so it seems.

Is there any interest in a Dutch version of this application? I would be up for the task!

**Comment by russelltrow** [comment]
Hi @EdgarPost, I've checked our website visitor stats and can see the Netherlands is no. 6 in our country list so a Dutch translation could well be valuable. @greenhsu123 what do you think?

**Comment by greenhsu123** [comment]
It would be great to have a Dutch version @EdgarPost, thank you!!

**Comment by EdgarPost** [comment]
Great, I am already working on it. 👍 

How would you like to handle the images, these need to be translated too. Are there source files somewhere that can be used?

**Comment by russelltrow** [comment]
@Jenya-design what would be the easiest way to handle translation of text on images in our training course? e.g. https://learn.greensoftware.foundation/introduction

**Comment by Jenya-design** [comment]
@russelltrow  I can add those images in Canva with editable text blocks, so anyone can use those as source files to edit the text
Does it work for you?

**Comment by russelltrow** [comment]
@Jenya-design I've just seen Canva has [automatic translation](https://learn.greensoftware.foundation/introduction). Perhaps it's worth testing this to save contributor effort?

**Comment by Jenya-design** [comment]
@russelltrow @EdgarPost please check Canva templates below
[English version](https://www.canva.com/design/DAFw4Qlvhzw/DDrFtOd-kACi_zrC2L4bSw/edit?utm_content=DAFw4Qlvhzw&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton) 
[Dutch auto translation](https://www.canva.com/design/DAFwyIBVUmE/x1mVEtM9CMZsIq4Xqr6Rzg/edit?utm_content=DAFwyIBVUmE&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton) 
Please make a copy before you edit the file
Let me know if you need any adjustments

**Comment by EdgarPost** [comment]
Thank you @Jenya-design! Amazing that it's possible to automatically translate texts in Canva, that already looks good. However, sometimes it makes more sense to keep words in English in certain contexts, especially in software development. For example, I would probably choose to keep Green _Software Principles_, and not translate it to _Groene softwareprincipes_.

I will make sure to make a copy of the file before I edit anything.

**Comment by Jenya-design** [comment]
Thank you @EdgarPost 
Unfortunately translation actually messes with the text blocks, though it keeps text style intact. I translated all and adjusted the blocks, to see worst case scenario from the design point. Sure it needs your review, I'm no translator and don't know a single word in Dutch :)

@russelltrow I've sent you the invitation to GSF Canva, please feel free to adjust the content of [Principles folder](https://www.canva.com/folder/FAFwyEcurCc) as you need

**Comment by russelltrow** [comment]
Hey @EdgarPost checking in to see if you are still progressing with your translation?

**Comment by EdgarPost** [comment]
Yes I am, but it's hard to find the time to work on it properly, sorry! 

Would it be a good idea to push some of my work to a remote branch?

**Comment by russelltrow** [comment]
Hi @EdgarPost, no need to apologise, we hugely appreciate your efforts!

If you could push to a remote branch please, we might be able to attract contributors from our side.

**Comment by russelltrow** [comment]
Closing as no updates since Feb
