### ISSUE TITLE
Analyse feedback collected from the Linux Foundation course

### ISSUE THREAD

**Issue by russelltrow** [Green-Software-Foundation/learn#199]
# Context

After completing [Green Software for Practitioners (LFC131)](https://training.linuxfoundation.org/training/green-software-for-practitioners-lfc131/) learners are asked for their feedback on the course and experience.

The survey includes the following questions:

* Did the course (text/video lectures, demo videos, etc.) cover the content you were expecting?
* Were the course assignments (knowledge checks, hands-on labs/exercises, if applicable) useful?
* What improvements can we make to this course (visual design, interactivities, multimedia)?
* What did you like best about this course?

I now have the responses from November 2022 - August 2023 in **Google Sheets**.

All of the questions above ask for both quantitive and qualitative feedback. For each question we have a sizeable number of text responses:

1. 1,016
2. 661
3. 4,203
4. 18,107

# Task

I would like to synthesize the feedback and extract actionable insights we can use to improve the course. I don't have enough data analysis experience to know where to start beyond throwing it at ChatGPT.

# Actions

- [ ] ?

**Comment by russelltrow** [comment]
@markus-gsf-seidl would you like access to the Google Sheet?

**Comment by markus-gsf-seidl** [comment]
@russelltrow Yes, please :)

**Comment by markus-gsf-seidl** [comment]
I've still working on it, but what can be said already is:

* More videos
* More videos
* More audio
* More interactivity
* More edutainment

There are over 1000 comments specifically mentioning this additionally some others that in one form or another.

The Q1 mentions a lot of

* More examples
* More Software Developer Content (which I classify every comment that wishes more practical knowledge)
* Missconceptions?
   * "the impact is mostly due at the production of end user devices"
   * 
* Some Bugs
   * Chapter 7 is too long
   * Australia and the Asia Pacific are missing from the maps (?)
   * Next/Back button wasn't clear and the colour scheme is hard on eyes
   * Note: Software Energy Monitoring is possible on system-level
   *

**Comment by russelltrow** [comment]
Really interesting and aligns with what I imagined. From my brief analysis there were lots of positive comments about the Informative content and clear explanations but room for improvement in structure & format.

It would be interesting to explore how it could be made more interactive and potentially have follow-on hands-on elements.

How are you doing the analysis? If we could get together a list of the bugs/snags then I can work on a revised version.

**Comment by markus-gsf-seidl** [comment]
It's manual work, I've looked at some automated stuff, but in the end I found them more work to include and get a grip of (and too pricey) as sifting through this in a few hours. Additionally you get a better feel and contact with the commentors.
There are so many mistypings of the word "video" you can't imagine, or "Intractive".
This improvement is sad: "Everything is very conceptual. No improvements are needed from my side."

I have categorized stuff, I can share a link to a document later with some explanation. So far it's like this:

![CleanShot 2023-11-07 at 06 32 45](https://github.com/Green-Software-Foundation/learn/assets/103509715/7c21b5fa-7fab-4eba-9d83-3fbdd7ab53f3)

Whereas "Video" is any improvement which mentions more interactivity, audio, non-text-content, better graphics, animations, etc. One commenter said, we should cater to all of his learning channels, not just the text path. Also including live-workshops, learning groups, etc.

Noise is everything that is not an improvement, in the end everything that is "good" should also be in there. Comments like "N/A", "none", etc. are not improvements (Q3).

There are around 40 things that I classified as bugs, which are things that the commenters said: "this is wrong". I didn't check these.

PS: I like this improvement request: "There are always scope of improvement" :D

**Comment by russelltrow** [comment]
Next step is for @russelltrow to build a v1.1 snagging list based on the bugs identified

**Comment by markus-gsf-seidl** [comment]
@russelltrow I sent you my modified excel sheet with the categories, did I?

**Comment by russelltrow** [comment]
Feedback has been reviewed and incorporated into content revisions for GSP v1.1
