### ISSUE TITLE
Japanese translation

### ISSUE THREAD

**Issue by russelltrow** [Green-Software-Foundation/learn#211]
I have just learned that a Japanese translation of the course has been produced by members of NTT Data. 

I am in the process of connecting with them to help them raise a Pull Request.

**Comment by russelltrow** [comment]
A PR has just been raised with the translation: https://github.com/Green-Software-Foundation/learn/pull/215

Is anyone able to review the content?

**Comment by russelltrow** [comment]
Hey @greenhsu123 as it doesn't look like we have anyone able to review shall we go ahead with merging the PR?

**Comment by greenhsu123** [comment]
I am happy for it to be merged. Thanks!

**Comment by russelltrow** [comment]
@greenhsu123 I'm very happy to report that the Japanese translation is now live: https://learn.greensoftware.foundation/ja/

Massive thanks to @YaSuenag and all the team at NTT.
