### ISSUE TITLE
GSP Training Graphics

### ISSUE THREAD

**Issue by NAMRATA-WOKE** [Green-Software-Foundation/learn#212]
- [ ] Yammer poster
- [ ] Social media social card and banners
- [ ] Website banner 
- [ ] Video banner
- [ ] Testimonials social cards 

_Supportive text_

- [ ] Become a Green Software Practitioner 
- [ ] A free online educational course on the principles of Green Software Engineering. 
- [ ] Meet a minimum and consistent level of understanding to decarbonize software, as recognized by over 60+ leading software and tech organizations, globally. 

Link: https://grnsft.org/practitioner/lf-exam

[Testimonials](https://docs.google.com/spreadsheets/d/1ErK2YF1T67T8IyrseX-dGv7-UO8EjhtsHGnpbd-zL1I/edit#gid=105059609)

**Comment by Jenya-design** [comment]
@NAMRATA-WOKE is [this issue](https://github.com/Green-Software-Foundation/writers/issues/185#issuecomment-1852086710) related to the same task?

**Comment by NAMRATA-WOKE** [comment]
@Jenya-design yes!

**Comment by Jenya-design** [comment]
@NAMRATA-WOKE please review (same update is posted in the [Issue #185 ](https://github.com/Green-Software-Foundation/writers/issues/185))

[Website / Homepage banner](https://drive.google.com/drive/folders/1a7734CVAuxXgCwiiSAdT71_j6qLIe0BN?usp=drive_link)

Social media social card  / Yammer poster (as it's an image for the post - square, less than 5000x5000, less than 10Mb - I think social cards can be used for Yammer)
[1200x1200]( https://www.canva.com/design/DAF5TJke6Ls/AykrSqgso8IyLNA1rS9SvQ/edit?utm_content=DAF5TJke6Ls&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton)

Testimonials social cards (I made 5, do you need all from the spreadsheet?)
[1200x1200](https://www.canva.com/design/DAF5OzPH_g4/khj1458s5P9Orb_F9dNY6w/edit?utm_content=DAF5OzPH_g4&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton)

Social media banners
[Twitter 1500x500](https://www.canva.com/design/DAF5O0BBitM/eFwfGUAjGIIwGWcv15SECA/edit?utm_content=DAF5O0BBitM&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton)
[LinkedIn 1128x191](https://www.canva.com/design/DAF5O-ZCIXM/MF7bEe4ep9OkRQEIeMh-Ag/edit?utm_content=DAF5O-ZCIXM&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton)

Video banner 
1920x1080 https://www.canva.com/design/DAF5Vn9p5j4/JGKGfnWdepnQETmekmJIyQ/edit?utm_content=DAF5Vn9p5j4&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton

LF page banner (can be reused for Meetup)
[1200x676](https://www.canva.com/design/DAF5VsC4qCk/sOwlA6BBRbzi9MrFhhRuLA/edit?utm_content=DAF5VsC4qCk&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton)

Mailchimp banners
[1200x600](https://www.canva.com/design/DAF5TFhiJTc/ASpGBYaxvKU5_Ek_Jbr6Vg/edit?utm_content=DAF5TFhiJTc&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton)
[1200x200](https://www.canva.com/design/DAF5TJke6Ls/AykrSqgso8IyLNA1rS9SvQ/edit?utm_content=DAF5TJke6Ls&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton)

Please let me know if you need any adjustments or variations
All links are generated for 'anyone to edit', please don't forget a copy if you're planning to make changes

**Comment by NAMRATA-WOKE** [comment]
@Jenya-design thesw look great. Can you add in:

Proud member of the GSF (use our logo)?

**Comment by russelltrow** [comment]
@NAMRATA-WOKE I've closed this issue as it's a duplicate of https://github.com/Green-Software-Foundation/learn/issues/214, would you mind putting any comments on their please
