### ISSUE TITLE
Promote Translations for Learn.GSF

### ISSUE THREAD

**Issue by NAMRATA-WOKE** [Green-Software-Foundation/learn#224]
Chinese: https://learn.greensoftware.foundation/zh-CN/
Japanese: https://learn.greensoftware.foundation/ja-JP/
Italian: https://learn.greensoftware.foundation/it/

**Comment by NAMRATA-WOKE** [comment]
Hi @Jenya-design so sorry for the last minute request, but can you create some social cards to promote the translations of our learning material? Links above.

**Comment by Jenya-design** [comment]
@NAMRATA-WOKE please check the preview attached, editable canva design [here](https://www.canva.com/design/DAGAyUWIN0k/E8kyLQYpVqw9asmdcw9qyg/edit?utm_content=DAGAyUWIN0k&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton)

![Image](https://github.com/Green-Software-Foundation/learn/assets/69306070/f89f00ff-55a3-4548-8459-db311a5b49e9)

![Image](https://github.com/Green-Software-Foundation/learn/assets/69306070/3d784d79-6ff6-4b48-aa85-c7f6818d13f6)

![Image](https://github.com/Green-Software-Foundation/learn/assets/69306070/176c372d-8cd9-4bfa-8cf4-2a50d477337e)

**Comment by russelltrow** [comment]
Published: https://www.linkedin.com/posts/green-software-foundation_greensoftware-greencomputing-sustainablesoftware-activity-7179130117644775427-LUIL?utm_source=share&utm_medium=member_desktop
