### ISSUE TITLE
Spanish Translation

### ISSUE THREAD

**Issue by ijasanchez** [Green-Software-Foundation/learn#225]
**Describe the solution you'd like**

I finished this course in English last year. It is fantastic. Green software is taking an interest in Spanish-speaking people, so the content should be in Spanish.  

**Describe alternatives you've considered**

I can contribute with Spanish translation, considering that some words and terms are more commonly used in English than Spanish, especially in software development. 

**Additional context**

Green software represents an innovative trend in the tech industry. The latest Software Architecture and Design Trends Report from InfoQ, released in April 2024, places green software within the innovator quadrant. 

In 2023, there were approximately 220,00 software developers in Mexico. Argentina had around 115,000, while Colombia totaled approximately 62,000 (source: statista.com). [Brazil, Chile, Mexico, Uruguay, and Colombia are your prime destinations for outsourcing to Latin America.](https://youteam.io/blog/best-latin-american-country-for-software-development-talent).

**Comment by aecurrie** [comment]
Note Alejandro is currently translating O'Reilly's Building Green Software
to Spanish

**Comment by russelltrow** [comment]
Hey @ijasanchez it is wonderful to hear from you and amazing to hear about your current passionate and efforts around Green IT.

We would absolutely love to have a Spanish translation for our Green Software Practitioner course.

**Comment by ijasanchez** [comment]
Hello everyone!

I started the Spanish translation this week. I reviewed the recommendations of @childotg for local execution, and it is working.

`yarn run start --locale sp` 

![image](https://github.com/Green-Software-Foundation/learn/assets/7343059/e896782d-5a85-47ad-867a-5d5f2c640539)


I finished the reduction of Welcome and Introduction. I will continue with @cindyerr the next week.

**Comment by russelltrow** [comment]
Hey @ijasanchez amazing to see that you have started the translation. As promised I've created instructions on how to translate the course:

https://github.com/Green-Software-Foundation/learn/blob/main/CONTRIBUTING.md#contributing-a-translation

This includes a template locale that you can refer to as required. Please let me know if you need any further support.

**Comment by ijasanchez** [comment]
Hi @russelltrow,

I applied the instructions, and it is working. Thank you for your support.

**Comment by russelltrow** [comment]
Hey @ijasanchez, how is the translation progressing?

**Comment by ijasanchez** [comment]
Hi @russelltrow,

I am resuming the translation this week. We hope to have the first draft by the beginning of July.

**Comment by altamayo02** [comment]
Hello everyone!

I am curious as to what Spanish locale is being worked on. I had been working on an es-CO translation in my own fork, unaware that there were other efforts being made!

I don't want to jump to conclusions, but @ijasanchez may have been working on the es-CO locale as well; if that's the case, I am Colombian, and I would like to offer my help in the translation. Could I join in?

**Comment by ijasanchez** [comment]
Hello @altamayo02, I am working on a fork in https://github.com/Smart-Green-IT/gsf-green-software-practitioner-training-sp/tree/translation-sp.

**Comment by ijasanchez** [comment]
Hi @russelltrow, @aecurrie  and @altamayo02,

I completed the translation for:

- Energy Efficiency
- Carbon Efficiency

I updated the translation branch with the last changes. I am working on [Smart-Green-IT/gsf-green-software-practitioner-training-sp@translation-sp](https://github.com/Smart-Green-IT/gsf-green-software-practitioner-training-sp/tree/translation-sp?rgh-link-date=2024-07-02T17%3A41%3A10Z).

I am working on Carbon Awareness.  @cindyerr and I will be finishing the next Friday.  

Please, remember the command for local execution:

`yarn run start --locale s`

**Comment by cindyerr** [comment]
Good morning @russelltrow, @aecurrie and @altamayo02,

I am working in the translation with @ijasanchez, and I am checking the wording to ensure that we use existing translations for Spanish concepts.

**Comment by ijasanchez** [comment]
Hi @russelltrow,

I created the pull request for Spanish translation: 
https://github.com/Green-Software-Foundation/learn/pull/233

**Comment by russelltrow** [comment]
Hey @ijasanchez @cindyerr that is fantastic news, thank you so much for your efforts.

I will review and come back with any comments first thing next week.

**Comment by russelltrow** [comment]
Thank you so so much @ijasanchez @cindyerr for all your efforts, the PR has just been merged and the translation is now live:

https://learn.greensoftware.foundation/es/
