### ISSUE TITLE
AC electron "flow" misunderstanding

### ISSUE THREAD

**Issue by lwilts** [Green-Software-Foundation/learn#239]
The "Climate Commitments" page contains multiple references to "electrons flowing into your device [coming from a (non-)renewable source]" - this is fundamentally incorrect. In an AC electricity supply electrons don't flow, they oscillate (by micrometers). A better term might be "the energy received by the device originates from..." or similar. 

https://github.com/Green-Software-Foundation/learn/blob/1aca5ffb67a37144b45a66e64de3516e459bc206/docs/climate-commitments.mdx?plain=1#L118

**Comment by russelltrow** [comment]
Hi @lwilts thank you so much for your feedback.

@greenhsu123 could you please respond accordingly.

**Comment by russelltrow** [comment]
Thank you for the feedback @lwilts, your revised wording has been merged in.
