### ISSUE TITLE
Update the information regarding the Paris Agreement

### ISSUE THREAD

**Issue by iliasbartolini** [Green-Software-Foundation/learn#240]
Currently in the section "Monitoring climate change" it is stated that 193 parties have signed the agreement.
Link to the section: https://learn.greensoftware.foundation/carbon-efficiency#climate-vs-weather

That is now incorrect, 197 parties have "signed" it  (198 if you count also the EU), but only 194 parties have "acceded or ratified" the agreement.

Source of the information: https://en.wikipedia.org/wiki/List_of_parties_to_the_Paris_Agreement

**Comment by russelltrow** [comment]
Thank you for raising this issue @iliasbartolini.

@greenhsu123 could you please review the above.

**Comment by greenhsu123** [comment]
Hi @iliasbartolini, thank you for flagging the above. We will look to update the content accordingly.

**Comment by russelltrow** [comment]
Thanks @iliasbartolini your proposed changes have been merged
