### ISSUE TITLE
Translation to pt-br

### ISSUE THREAD

**Issue by tfalc** [Green-Software-Foundation/learn#243]
Hello!

I look forward to working on a translation of the material to pt-br. 
I have already downloaded the template, and now I am opening this issue to discuss the images that I would like to translate. 

How can we work this? Should I download it separately? Are the images ready to edit the texts? Do I need any software to edit it? 

Best regards!

**Comment by russelltrow** [comment]
Hi @tfalc, it is wonderful to hear from you and that you would like to work on a translation.

Here is a [Canva template]( https://www.canva.com/design/DAGUNp-AIOA/-dUxBsHoUtYEuKSAlW1rUg/edit?utm_content=DAGUNp-AIOA&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton) on which you can translate the images.

Please let me know if you require any further support.

**Comment by tfalc** [comment]
Hey, @russelltrow ! 

I just finished the first edition (which may need some revision, maybe!?). How can I merge with the project? I forked it and already pushed my version. I need a branch to create a PR. Am I able to create one? I'm new to this world of working on open-source projects.

**Comment by russelltrow** [comment]
Hey @tfalc, the translation looks fantastic! 

I've just reviewed your Pull Request and it is ready to be merged. I just need you to follow these instructions to comply with the DCO requirement: https://github.com/Green-Software-Foundation/learn/pull/246/checks?check_run_id=34380970681

Once the DCO check passes I'll merge and publish the translation.

Thank you again for all your efforts! 🎉

**Comment by russelltrow** [comment]
Hey @tfalc the translation is now live https://learn.greensoftware.foundation/pt-BR/ 🎉 🎉 🎉

**Comment by russelltrow** [comment]
@tfalc with your amazing contribution please do register as a Green Software Champion if you haven't already

https://champions.greensoftware.foundation/
